### ISSUE TITLE
Error during set group icon.

### ISSUE THREAD

**Issue by ShamsSayied** [tjackenpacken/taskbar-groups#11]
When I want to set a png icon as group icon then this error occurred.

Icon Link: https://www.iconfinder.com/icons/4202103/download/png/512

Error Log:
=============================================================
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.OutOfMemoryException: Out of memory.
   at System.Drawing.Image.FromFile(String filename, Boolean useEmbeddedColorManagement)
   at System.Drawing.Image.FromFile(String filename)
   at TaskbarGroupsClient.frmNewGroup.cmdAddGroupIcon_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Label.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4300.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
TaskbarGroupsClient
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///D:/All%20Software/Rare%20Software/Taskbar%20groups/Taskbar%20groups.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4270.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4300.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4300.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by tjackenpacken** [comment]
I'm getting 403 access denied when trying to reach the link

**Comment by tjackenpacken** [comment]
> 
> 
> When I want to set a png icon as group icon then this error occurred.
> 
> Icon Link: https://www.iconfinder.com/icons/4202103/download/png/512
> # Error Log:
> 
> See the end of this message for details on invoking
> just-in-time (JIT) debugging instead of this dialog box.
> 
> ************** Exception Text **************
> System.OutOfMemoryException: Out of memory.
> at System.Drawing.Image.FromFile(String filename, Boolean useEmbeddedColorManagement)
> at System.Drawing.Image.FromFile(String filename)
> at TaskbarGroupsClient.frmNewGroup.cmdAddGroupIcon_Click(Object sender, EventArgs e)
> at System.Windows.Forms.Control.OnClick(EventArgs e)
> at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
> at System.Windows.Forms.Control.WndProc(Message& m)
> at System.Windows.Forms.Label.WndProc(Message& m)
> at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
> at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
> at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
> ## ************** Loaded Assemblies **************
> mscorlib
> Assembly Version: 4.0.0.0
> Win32 Version: 4.8.4300.0 built by: NET48REL1LAST_C
> CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
> ## TaskbarGroupsClient
> Assembly Version: 1.0.0.0
> Win32 Version: 1.0.0.0
> CodeBase: file:///D:/All%20Software/Rare%20Software/Taskbar%20groups/Taskbar%20groups.exe
> ## System.Windows.Forms
> Assembly Version: 4.0.0.0
> Win32 Version: 4.8.4270.0 built by: NET48REL1LAST_C
> CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
> ## System
> Assembly Version: 4.0.0.0
> Win32 Version: 4.8.4300.0 built by: NET48REL1LAST_C
> CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
> ## System.Drawing
> Assembly Version: 4.0.0.0
> Win32 Version: 4.8.4084.0 built by: NET48REL1
> CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
> ## System.Configuration
> Assembly Version: 4.0.0.0
> Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
> CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
> ## System.Core
> Assembly Version: 4.0.0.0
> Win32 Version: 4.8.4300.0 built by: NET48REL1LAST_C
> CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
> ## System.Xml
> Assembly Version: 4.0.0.0
> Win32 Version: 4.8.4084.0 built by: NET48REL1
> CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
> 
> ************** JIT Debugging **************
> To enable just-in-time (JIT) debugging, the .config file for this
> application or computer (machine.config) must have the
> jitDebugging value set in the system.windows.forms section.
> The application must also be compiled with debugging
> enabled.
> 
> For example:
> 
> When JIT debugging is enabled, any unhandled exception
> will be sent to the JIT debugger registered on the computer
> rather than be handled by this dialog box.

I'm getting 403 access denied when trying to reach the link

**Comment by ShamsSayied** [comment]
https://www.iconfinder.com/icons/4202103/office_logo_microsoft_ms_social_social_media_icon

**Comment by ShamsSayied** [comment]
Here I also attach a video for the bug adding png icon.
https://drive.google.com/file/d/1DMtjv54Xt46EHUJpnBR_LQp4fca12Y6w/view?usp=sharing
